version: '3.7'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/things/volume/jenkins_home/:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      default:
        ipv4_address: 172.21.0.2
    user: root
    entrypoint: >
      /bin/bash -c "
      if [ ! -S /var/run/docker.sock ]; then
        echo 'Docker socket not found, exiting';
        exit 1;
      fi;
      chown jenkins:docker /var/run/docker.sock;
      /usr/local/bin/jenkins.sh"

  nexus:
    image: sonatype/nexus3
    volumes:
      - /mnt/things/volume/nexus_data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      default:
        ipv4_address: 172.21.0.3

networks:
  default:
    external:
      name: elk_network

volumes:
  nexus-data:
